# in config/database.yml
development:
  adapter: mysql2
  encoding: utf8
  database: 'sinatra'
  username: 'root'
  password: ''
  host: localhost
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: 'sinatra'
  username: 'root'
  password: ''
  host: localhost
  port: 3306